name: Docker build and push

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  GH_REPO: ${{ github.repository }}
  APP_NAME: alpine-python


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Log in to registry
        # This is where you will update the personal access token to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push Docker images
        run: |
          for dir in */; do
            if [ -n "$(git diff --name-only ${{ github.ref }}~ -- $dir)" ]; then
              echo "Building $dir"
              cd "$dir" || continue
              IMAGE_NAME="${{ env.REGISTRY }}/${{ env.GH_REPO }}:${dir%/}"
              docker build -t "$IMAGE_NAME" .
              docker push "$IMAGE_NAME"
              cd ..
            else
              echo "No changes detected in $dir, skipping Docker build."
            fi
          done

